.\"                                      Hey, EMACS: -*- nroff -*-
.TH MIGRATE-REPOSITORY 1 "2009-02-07"
.SH NAME
migrate-repository \- Migration of pre 0.4.5 SQLAlchemy migrate repositories
.SH SYNOPSIS
.B migrate-repository
.I repository_directory

.SH DESCRIPTION
SQLAlchemy migrate uses a new repository format since version 0.4.5.

All documentation for
.B migrate
is available in HTML format under /usr/share/doc/python-migrate/html.
.SH SEE ALSO
migrate's homepage at
.B
http://code.google.com/p/sqlalchemy-migrate/
.SH AUTHOR
migrate was written by Evan Rosson <evan.rosson@gmail.com>. The
package was taken over by a group of volunteers when Evan had no free
time for maintaining it.
.PP
This manual page was written by Jan Dittberner <jan@dittberner.info>,
for the Debian project (but may be used by others).
