.\"                                      Hey, EMACS: -*- nroff -*-
.TH MIGRATE 1 "2006-12-25"
.SH NAME
migrate \- Database schema migration for SQLAlchemy
.SH DESCRIPTION
migrate provides database schema migration for SQLAlchemy. The migrate command
is used to work with database schema revisions.

All documentation for
.B migrate
is available in HTML format under /usr/share/doc/python-migrate/html.
.SH SEE ALSO
migrate's homepage at
.B
http://code.google.com/p/sqlalchemy-migrate/
.SH AUTHOR
migrate was written by Evan Rosson <evan.rosson@gmail.com>. The
package was taken over by a group of volunteers when Evan had no free
time for maintaining it.
.PP
This manual page was written by Jan Dittberner <jan@dittberner.info>,
for the Debian project (but may be used by others).
